### ISSUE TITLE
19.10 Banner for beta and final

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/assets#7]
@Udara-U3 & @raniaamina We are rapidly approaching 19.10 beta (mid Sept) and 19.10 release (middle of October) Need one of your wonderful artistic banners :) TIA.
--

**Comment by fossfreedom** [comment]
Hi @Udara-U3 & @raniaamina - quick ping on the above - are you able to help in this cycle please?

**Comment by uD4ra** [comment]
Hi David,
I'll do something for this for sure asap, sorry for the late reply because of my busy schedule. 🤦‍♂️

**Comment by fossfreedom** [comment]
wonderful! cheers and much appreciated 👍

**Comment by uD4ra** [comment]
Here you go :) I just commited [New Banners](https://github.com/UbuntuBudgie/assets/commit/48415fdd3d35d022c748fe83547cf8e69bc40b10) here. check them out and please let me know if there is any modifications.

**Comment by fossfreedom** [comment]
Absolutely stunning :)

Really is - much appreciated!
